services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: rimmi
            POSTGRES_PASSWORD: Coderkudi02
            POSTGRES_DB: habittracker
        ports:
            - '5432:5432'
        volumes:
            - ./db_data:/var/lib/postgresql/data
        ports:
            - '5433:5432'
        restart: always

    backend:
        build: .
        ports:
            - '${PORT}:${PORT}'
        environment:
            DATABASE_URL: ${DATABASE_URL}
            PORT: ${PORT}
        depends_on:
            - postgres
        restart: always
