services:
    backend:
        image: habittracker-backend
        ports:
            - '8000:8000'
        env_file:
            - .env
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5433/${POSTGRES_DB}
        ports:
            - '5433:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
