name: Close Stale Issues and PRs

on:
    schedule:
        - cron: '0 2 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v9
              with:
                  days-before-stale: 14
                  days-before-close: 7
                  stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs.'
                  stale-pr-message: 'This PR has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs.'
                  close-issue-message: 'Closing this issue due to prolonged inactivity.'
                  close-pr-message: 'Closing this PR due to prolonged inactivity.'
